package eu.sesma.paraguas.api.ds_model

object ModelConstants {

    // Field strings
    const val FIELD_TITLE = "title"
    const val FIELD_REGIONS = "regions"
    const val FIELD_SEVERITY = "severity"
    const val FIELD_TIME = "time"
    const val FIELD_DESCRIPTION = "description"
    const val FIELD_EXPIRES = "expires"
    const val FIELD_URI = "uri"
    const val FIELD_SUMMARY = "summary"
    const val FIELD_ICON = "icon"
    const val FIELD_DATA = "data"
    const val FIELD_LATITUDE = "latitude"
    const val FIELD_LONGITUDE = "longitude"
    const val FIELD_TIMEZONE = "timezone"
    const val FIELD_OFFSET = "offset"
    const val FIELD_CURRENTLY = "currently"
    const val FIELD_MINUTELY = "minutely"
    const val FIELD_HOURLY = "hourly"
    const val FIELD_DAILY = "daily"
    const val FIELD_ALERTS = "alerts"
    const val FIELD_FLAGS = "flags"
    const val FIELD_DARKSKY_UNAVAILABLE = "darksky-unavailable"
    const val FIELD_DARKSKY_STATIONS = "darksky-stations"
    const val FIELD_DATAPOINT_STATIONS = "datapoint-stations"
    const val FIELD_ISD_STATIONS = "isd-stations"
    const val FIELD_LAMP_STATIONS = "lamp-stations"
    const val FIELD_MADIS_STATIONS = "madis-stations"
    const val FIELD_METAR_STATIONS = "metar-stations"
    const val FIELD_METNO_LICENSE = "metno-license"
    const val FIELD_SOURCES = "sources"
    const val FIELD_UNITS = "units"
    const val FIELD_SUNSET_TIME = "sunsetTime"
    const val FIELD_SUNRISE_TIME = "sunriseTime"
    const val FIELD_MOON_PHASE = "moonPhase"
    const val FIELD_NEAREST_STORM_DISTANCE = "nearestStormDistance"
    const val FIELD_NEAREST_STORM_BEARING = "nearestStormBearing"
    const val FIELD_PRECIP_INTENSITY = "precipIntensity"
    const val FIELD_PRECIP_INTENSITY_MAX = "precipIntensityMax"
    const val FIELD_PRECIP_INTENSITY_MAX_TIME = "precipIntensityMaxTime"
    const val FIELD_PRECIP_PROBABILITY = "precipProbability"
    const val FIELD_PRECIP_TYPE = "precipType"
    const val FIELD_PRECIP_ACCUMULATION = "precipAccumulation"
    const val FIELD_TEMPERATURE = "temperature"
    const val FIELD_TEMPERATURE_MIN = "temperatureMin"
    const val FIELD_TEMPERATURE_MIN_TIME = "temperatureMinTime"
    const val FIELD_TEMPERATURE_MAX = "temperatureMax"
    const val FIELD_TEMPERATURE_MAX_TIME = "temperatureMaxTime"
    const val FIELD_APPARENT_TEMPERATURE = "apparentTemperature"
    const val FIELD_APPARENT_TEMPERATURE_MIN = "apparentTemperatureMin"
    const val FIELD_APPARENT_TEMPERATURE_MIN_TIME = "apparentTemperatureMinTime"
    const val FIELD_APPARENT_TEMPERATURE_MAX = "apparentTemperatureMax"
    const val FIELD_APPARENT_TEMPERATURE_MAX_TIME = "apparentTemperatureMaxTime"
    const val FIELD_DEW_POINT = "dewPoint"
    const val FIELD_WIND_SPEED = "windSpeed"
    const val FIELD_WIND_BEARING = "windBearing"
    const val FIELD_CLOUD_COVER = "cloudCover"
    const val FIELD_HUMIDITY = "humidity"
    const val FIELD_PRESSURE = "pressure"
    const val FIELD_VISIBILITY = "visibility"
    const val FIELD_OZONE = "ozone"
    const val FIELD_UV_INDEX = "uvIndex"
    const val FIELD_UV_INDEX_TIME = "uvIndexTime"
    const val FIELD_APPARENT_TEMPERATURE_LOW = "apparentTemperatureLow"
    const val FIELD_APPARENT_TEMPERATURE_LOW_TIME = "apparentTemperatureLowTime"
    const val FIELD_APPARENT_TEMPERATURE_HIGH = "apparentTemperatureHigh"
    const val FIELD_APPARENT_TEMPERATURE_HIGH_TIME = "apparentTemperatureHighTime"
    const val FIELD_TEMPERATURE_LOW = "temperatureLow"
    const val FIELD_TEMPERATURE_LOW_TIME = "temperatureLowTime"
    const val FIELD_TEMPERATURE_HIGH = "temperatureHigh"
    const val FIELD_TEMPERATURE_HIGH_TIME = "temperatureHighTime"


    // Icon enum strings
    const val ICON_CLEAR_DAY = "clear-day"
    const val ICON_CLEAR_NIGHT = "clear-night"
    const val ICON_RAIN = "rain"
    const val ICON_SNOW = "snow"
    const val ICON_SLEET = "sleet"
    const val ICON_WIND = "wind"
    const val ICON_FOG = "fog"
    const val ICON_CLOUDY = "cloudy"
    const val ICON_PARTLY_CLOUDY_DAY = "partly-cloudy-day"
    const val ICON_PARTLY_CLOUDY_NIGHT = "partly-cloudy-night"
    const val ICON_HAIL = "hail"
    const val ICON_THUNDERSTORM = "thunderstorm"
    const val ICON_TORNADO = "tornado"

    // Language enum strings
    const val LANGUAGE_ARABIC = "ar"
    const val LANGUAGE_AZERBAIJANI = "az"
    const val LANGUAGE_BELARUSIAN = "be"
    const val LANGUAGE_BOSNIAN = "bs"
    const val LANGUAGE_CZECH = "cs"
    const val LANGUAGE_GERMAN = "de"
    const val LANGUAGE_GREEK = "el"
    const val LANGUAGE_ENGLISH = "en"
    const val LANGUAGE_SPANISH = "es"
    const val LANGUAGE_FRENCH = "fr"
    const val LANGUAGE_CROATIAN = "hr"
    const val LANGUAGE_HUNGARIAN = "hu"
    const val LANGUAGE_INDONESIAN = "id"
    const val LANGUAGE_ITALIAN = "it"
    const val LANGUAGE_ICELANDIC = "is"
    const val LANGUAGE_CORNISH = "kw"
    const val LANGUAGE_NORWEGIAN_BOKMAL = "nb"
    const val LANGUAGE_DUTCH = "nl"
    const val LANGUAGE_POLISH = "pl"
    const val LANGUAGE_PORTUGUESE = "pt"
    const val LANGUAGE_RUSSIAN = "ru"
    const val LANGUAGE_SLOVAK = "sk"
    const val LANGUAGE_SERBIAN = "sr"
    const val LANGUAGE_SWEDISH = "sv"
    const val LANGUAGE_TETUM = "tet"
    const val LANGUAGE_TURKISH = "tr"
    const val LANGUAGE_UKRAINIAN = "uk"
    const val LANGUAGE_PIG_LATIN = "x-pig-latin"
    const val LANGUAGE_SIMPLIFIED_CHINESE = "zh"
    const val LANGUAGE_TRADITIONAL_CHINESE = "zh-tw"

    // PrecipitationType enum string
    const val PRECIPITATION_RAIN = "rain"
    const val PRECIPITATION_SNOW = "snow"
    const val PRECIPITATION_SLEET = "sleet"
    const val PRECIPITATION_HAIL = "hail"

    // Units enum strings
    const val UNIT_US = "us"
    const val UNIT_SI = "si"
    const val UNIT_CA = "ca"
    const val UNIT_UK = "uk"
    const val UNIT_UK2 = "uk2"
    const val UNIT_AUTO = "auto"
}
